### ISSUE TITLE
Sailthru Documentation not updated!

### ISSUE THREAD

**Issue by seanarnold** [sailthru/sailthru-ruby-client#57]
This project refers to the Sailthru documentation pages (http://getstarted.sailthru.com/developers/api-libraries/ruby) but they are so out of date its not funny.
I contacted Sailthru support about this but it still hasn't been updated.

This isn't an issue for a project but if you're going to link somewhere make sure its useful

**Comment by rreusser** [comment]
Looks to be current: http://getstarted.sailthru.com/new-for-developers-overview/api-client-library/ruby-gem/

**Comment by rreusser** [comment]
Wait, sorry. My note was only a correction for the link. The documentation itself is unchanged and still not-humorously outdated from what I can tell. `create_new_user` doesn't exist anymore…

**Comment by georgekliao** [comment]
@seanarnold @rreusser thanks for pointing this out. We will be updating the readme with the correct links shortly. As for the out of date documentation site, I will follow up separately with our documentation team on the appropriate changes that need to be made.

Please stay tuned.

**Comment by rreusser** [comment]
@georgekliao Awesome, thanks!

**Comment by georgekliao** [comment]
@rreusser just following up on this. we removed the incorrect create_new_user documentation as well as updated the link to the readme. can we close this out?

**Comment by rreusser** [comment]
LGTM! Thanks!
