### ISSUE TITLE
uninitialized constant Sailthru::Client::VERSION

### ISSUE THREAD

**Issue by seanarnold** [sailthru/sailthru-ruby-client#58]
When calling send_email like this: 
`response = sailthru.send_email(template, email_address, params, options)`

where the variables are: 
`template = "Test_template"`,
`email_address = "test@test.com"`,
`params = {}`,
`options = {}`

I get `NameError: uninitialized constant Sailthru::Client::VERSION`

This is on Rails 4.0.0 with ruby 1.9.3-p484

**Comment by dabobert** [comment]
doing
   gem 'sailthru-client', :require => 'sailthru'

worked for me as well

**Comment by germs12** [comment]
I am having this issue, but I'm not using Rails.  I am using a basic ruby script.  Any idea how to fix it in that case?

**Comment by spc9999** [comment]
germs12, what error are you getting? There should not be an issue with Ruby, you just require the gem. Here's a sample gist which will send a test email  

https://gist.github.com/spc9999/fd6b1b99ddfc2ba20c87

**Comment by lindsayneubauer** [comment]
@germs12 @seanarnold  @biegel Just merged the fix requiring version (https://github.com/sailthru/sailthru-ruby-client/pull/68). Would like to confirm that we can close this issue. If not, please provide me with more info on the issue. Thanks!
