### ISSUE TITLE
Usage of a named method, `send` for sending templates

### ISSUE THREAD

**Issue by BenMorganIO** [sailthru/sailthru-ruby-client#62]
While using the API client, I noticed that there's been usage of the `send` method to send emails. This is isn't great since `send` is used in ruby to "send" methods to an object.

Is it possible to rename the method to `send_email` or make an `Email` class and perhaps use the `new` method via `initialize` instead?

**Comment by BenMorganIO** [comment]
It looks this change was already made in the source. Docs are out of date.

**Comment by lindsayneubauer** [comment]
@BenMorganIO following up on this. The documentation looks to now be up to date with `send_email`. Can we close this out?
