### ISSUE TITLE
Setting "Test Vars" in template preview through the API on template creation. 

### ISSUE THREAD

**Issue by sollipse** [sailthru/sailthru-ruby-client#66]
This may be the wrong place to ask this, but I had some trouble trying to track down a forum for these kinds of inquiries. 

Does Sailthru currently support setting testvariables -- 
![screen shot 2015-09-02 at 1 43 43 pm](https://cloud.githubusercontent.com/assets/4791393/9643747/a79b125e-5178-11e5-85f9-946bfbe4c429.png)

Through an API call? My intent is to be able to programmatically create a template that has all these variables pre-set for a preview, but not set in the standard "Variable hash": 
![screen shot 2015-09-02 at 1 44 56 pm](https://cloud.githubusercontent.com/assets/4791393/9643800/d4f05f48-5178-11e5-9d4e-2dd2b500c465.png)

Because variables set there will over-write variables you try to set through API calls when you run ```send_email(template, email, vars)```

**Comment by lindsayneubauer** [comment]
@sollipse This is possible by specifying `test_vars` in your saveTemplate POST. See https://github.com/sailthru/sailthru-ruby-client/blob/master/test/sailthru/template_test.rb#L42-L49 for an example.

**Comment by lindsayneubauer** [comment]
@sollipse Our documentation team has added information on how to use this in our documentation: http://getstarted.sailthru.com/new-for-developers-overview/email-and-user-profiles/template/

**Comment by sollipse** [comment]
Thanks so much for the info, and for adding it to your documentation!

**Comment by lindsayneubauer** [comment]
@sollipse No problem! Can you close out this issue?

**Comment by sollipse** [comment]
Of course!
