### ISSUE TITLE
API docs out of date

### ISSUE THREAD

**Issue by wulftone** [sailthru/sailthru-ruby-client#74]
See https://getstarted.sailthru.com/developers/api-client/ruby/, there isn't anything about the job APIs.  Not sure what else is missing!  Documentation is pretty thin in general, could use a lot more examples on how to use this client.

**Comment by lindsayneubauer** [comment]
Thanks for pointing this out - Updated the README to point to our docs site (where updates/examples will be added/managed going forward)
