### ISSUE TITLE
What is the proper way of stubbing out the Sailthru Client?

### ISSUE THREAD

**Issue by reidcooper** [sailthru/sailthru-ruby-client#76]
For our tests we are looking for a way to stub out the Sailthru client. What is the most proper way of doing so or preferred way on your end?

Otherwise, I could just VCR the response however I am looking to not have to do that; only on integration/feature specs.

**Comment by lindsayneubauer** [comment]
There is no preferred way. If you have a proposal for how we should adjust the library to make it easier to test we are happy to hear it and will investigate doing that work.

**Comment by josecoelho** [comment]
@reidcooper the way to stub depends on what's the library that you are using for testing.

Example for [`rspec-mocks`](https://rspec.info/documentation/3.4/rspec-mocks/):
```ruby
let(:sailthru_client) { instance_double(Sailthru::Client) }
let(:sailtrhu_user_response) do
  { 
    vars : {
      Var_1: 'var_1_val',
      Var_2: 'var_2_val'
    },
  }
end

before do
  # returning double when instantiating Client
  allow(Sailthru::Client).to receive(:new).with(api_key, api_secret) { sailthru_client }
  # returning data when calling a method
  allow(sailtrhu_client).to receive(:get_user_by_sid).with('4e2879472d7acd6d97144f9e', {vars: 1}) { sailtrhu_response }
end

it 'does something' do
  # execute your code expecting user vars from Sailthru Client
end
```

Please, let me know if you need any further information.
