### ISSUE TITLE
[enhancement] Schedule list

### ISSUE THREAD

**Issue by tostasqb** [sailthru/sailthru-ruby-client#78]
Would be very nice to make available the list of all scheduled emails from the "Schedule Send Log" page on Sailthru. Maybe make it searchable by email (at least) and template.

Note: The "Scheduled Send Log" is also not filterable on the Sailthru platform but would be a nice feature.

**Comment by josecoelho** [comment]
Hi @tostasqb. We appreciate your suggestion, we have a similar request on our records. I've updated it with your suggestion as well.

Please, reopen the issue if you have any futher questions or get in touch with our support team via support@sailthru.com.
