### ISSUE TITLE
Does this use TLS1.2?

### ISSUE THREAD

**Issue by wesdotcool** [sailthru/sailthru-ruby-client#84]
I received this message from Sailthru

> On Sept. 1, 2020, we will disable TLS1.0 and TLS1.1 access to the Sailthru API. To prevent a service interruption, your integration must begin using TLS1.2 before that time. After Sept. 1 at 12:01 a.m. EST, we will not accept requests to our API sent over TLS1.0 or TLS1.1. The connection will be rejected.

Does this gem use TLS1.2 or will it be affected by this update?

**Comment by lindsaycooper** [comment]
The most up to date gem ([4.3.0](https://rubygems.org/gems/sailthru-client/versions/4.3.0)) has been updated to use TLS1.2.
The specific code for this can be found [here](https://github.com/sailthru/sailthru-ruby-client/blob/master/lib/sailthru/client.rb#L883)
